version: '3'

vars:
  BIN:   './bin/gtom-proxy'
  GIT_COMMIT:
    sh: git log -n 1 --format=%h

tasks:
  default:
    desc: "Build the gtom proxy for mac/amd64 platforms."
    cmds:
      - go build -o "{{.BIN}}.${GOOS}.${GOARCH}" -ldflags "-X main.commit={{.GIT_COMMIT}}"
    env:
      GOOS:   'darwin'
      GOARCH: 'amd64'

  linux:
    desc: "Build the gtom proxy for linux/amd64 platforms."
    cmds:
      - go build -o "{{.BIN}}.${GOOS}.${GOARCH}" -ldflags "-X main.commit={{.GIT_COMMIT}}"
    env:
      GOOS:   'linux'
      GOARCH: 'amd64'
